Touch events support
elixir-wallaby/wallaby pull request #480
Opened 2019-11-20 07:35 UTC by jangromko

Added support for touch events:
- touch_down,
- touch_up,
- tap,
- touch_move,
- touch_scroll.

Additionally, also support for getting element size and location was added.

2019-11-20 10:00 UTC, michallepicki commented on integration_test/cases/browser/touch_scroll_test.exs
> +      assert visible?(page, Query.text("End", count: 0))
not sure how this works but shouldn't the above be `assert has?` with `count: 0` instead of `assert visible?` ?

2019-11-22 16:21 UTC, aaronrenner commented
@jangromko Thanks for the PR! ❤️ 

It looks like this diff includes some formatting changes which were just fixed in master. Would you mind rebasing?

2020-05-07 19:32 UTC, bartblast commented
Hey, any plans to merge this?

2020-05-07 19:39 UTC, michallepicki commented
@jangromko I can take over and try to figure out a common API we could support for both old and new protocol through web_driver_client if you don't feel like updating/rebasing this

2020-11-19 10:58 UTC, jangromko commented
Updated and ready for review.

2020-12-06 16:29 UTC, mhanberg requested changes
Thanks for this!

Please apply the doc suggestions and I can merge this.

2020-12-06 16:29 UTC, mhanberg commented on lib/wallaby/browser.ex
> +  Moves touch pointer (finger, stylus etc.) on the screen to the point determinated by the given coordinates.
```suggestion
  Moves the touch pointer (finger, stylus etc.) on the screen to the point determined by the given coordinates.
```

2020-12-06 16:29 UTC, mhanberg commented on lib/wallaby/element.ex
> +  Touches and holds the element on its top-left corner plus optional offset.
```suggestion
  Touches and holds the element on its top-left corner plus an optional offset.
```

2020-12-06 16:29 UTC, mhanberg commented on lib/wallaby/element.ex
> +  Returns tuple {width, height} with size of the given element.
```suggestion
  Returns a tuple `{width, height}` with the size of the given element.
```

2020-12-06 16:29 UTC, mhanberg commented on lib/wallaby/element.ex
> +  Returns tuple {x, y} with coordinates of the left-top corner of given element.
```suggestion
  Returns a tuple `{x, y}` with the coordinates of the left-top corner of given element.
```

2020-12-06 16:29 UTC, mhanberg commented on lib/wallaby/webdriver_client.ex
> +  Touches screen at the given position.
```suggestion
  Touches the screen at the given position.
```

2020-12-06 16:29 UTC, mhanberg commented on lib/wallaby/webdriver_client.ex
> +  Moves touch pointer (finger, stylus etc.) on the screen to the point determinated by the given coordinates.
```suggestion
  Moves the touch pointer (finger, stylus etc.) on the screen to the point determined by the given coordinates.
```

2020-12-06 16:29 UTC, mhanberg commented on lib/wallaby/webdriver_client.ex
> +  Returns tuple {width, height} with size of the given element.
```suggestion
  Returns a tuple `{width, height}` with the size of the given element.
```

2020-12-06 16:29 UTC, mhanberg commented on lib/wallaby/webdriver_client.ex
> +  Returns tuple {x, y} with coordinates of the top-left corner of given element.
```suggestion
  Returns a tuple `{x, y}` with the coordinates of the top-left corner of given element.
```

2020-12-07 12:48 UTC, mhanberg approved these changes

2020-12-07 12:50 UTC, merged