Only spawn a browser when using the `feature` macro, not normal `test`s
elixir-wallaby/wallaby pull request #795
Opened 2024-12-29 21:04 UTC by s3cur3

This fixes an unintended behavior where having `use Wallaby.Feature` at the top of your module would cause a browser to be spawned for every test in the module, not just `feature` tests. The result is that if you had a large test module, most of which used the normal `test` macro and one of which used the `feature` macro, every test would take a minimum of a third of a second or more.

I also took the liberty to check and see in the `setup` block if we already had a `:session`, and if so, avoid spawning a second. I don't *think* anyone was relying on the behavior where a second browser was being spawned if you had `use Wallaby.Feature` at both the top of the module and a `describe` block.

Resolves #794

2024-12-29 22:59 UTC, mhanberg requested changes

2024-12-29 22:59 UTC, mhanberg commented on lib/wallaby/feature.ex
> +        already_has_session? = is_map_key(context, :session)
Let's not deal with this in this pull request and do a second one. 

This might be better to emit a warning rather than be silent.

2024-12-29 22:59 UTC, mhanberg commented on lib/wallaby/feature.ex
> +        feature_test? = context[:feature] == true
I think here you want to check `context[:test_type] == :feature`

2024-12-29 22:59 UTC, mhanberg commented on lib/wallaby/feature.ex
> +        feature_test? = context[:feature] == true
Also I would just inline this. It's self explanatory.

2024-12-29 22:59 UTC, mhanberg commented
The tests might fail a bunch but you don't have to worry about it.

2024-12-31 14:37 UTC, s3cur3 commented
Changes made! ☺️

2025-01-03 16:00 UTC, mhanberg approved these changes

2025-01-03 16:00 UTC, merged